package biz.lermitage.sub.model

enum class Category(val label: String) {

    ADOPT_OPEN_JDK("AdoptOpenJDK"),
    ADOPTIUM("Adoptium"),
    DATABASE("Database"),
    GO("Go"),
    GRADLE("Gradle"),
    GPG("GPG"),
    INKSCAPE("Inkscape"),
    JAVA("Java"),
    JDK("JDK"),
    CODECS("Codecs"),
    LIBRARY("Library"),
    MARIADB("MariaDB"),
    MAVEN("Maven"),
    NODEJS("NodeJS"),
    OS("Operating System"),
    PODCAST("Podcast"),
    POSTGRESQL("PostgreSQL"),
    PYTHON("Python"),
    RHEL("Red Hat Enterprise Linux"),
    SPRING_FRAMEWORK("Spring Framework"),
    SVG_EDITOR("SVG editor"),
    VIDEO_PLAYER("Video player"),
    VERACRYPT("VeraCrypt"),
    REDIST("Redistributable Runtimes"),
    VLC("VLC"),
    MS_WINDOWS("MS Windows"),
}
